/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4b9b76bb-3032-47a4-9f99-07d9aaa92fc3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GL38vXs0Q",
    "aws_user_pools_web_client_id": "1qqj5b3ren68p3pl6a5e3e19ql",
    "oauth": {}
};


export default awsmobile;
